const coupons = [
  {
    id: 1,
    storeName: "Example Fashion",
    title: "20% Off Your Order",
    description: "Save 20% on selected apparel and accessories.",
    code: "SAVE20",
    discount: "20% OFF",
    category: "Fashion",
    expirationDate: "2026-12-31",
    verified: true,
    featured: true,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 2,
    storeName: "Tech Haven",
    title: "$50 Off Laptops",
    description: "Get $50 off when you buy any laptop over $500.",
    code: "LAPTOP50",
    discount: "$50 OFF",
    category: "Electronics",
    expirationDate: "2026-10-15",
    verified: true,
    featured: true,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 3,
    storeName: "Burger Kingly",
    title: "Free Fries with Any Meal",
    description: "Enjoy a free medium fries with the purchase of any combo meal.",
    code: "FRIESPLS",
    discount: "FREE FRIES",
    category: "Food",
    expirationDate: "2026-09-30",
    verified: true,
    featured: false,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 4,
    storeName: "Global Airways",
    title: "15% Off Domestic Flights",
    description: "Book early and save 15% on all domestic flights.",
    code: "FLY15",
    discount: "15% OFF",
    category: "Travel",
    expirationDate: "2026-11-20",
    verified: true,
    featured: true,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 5,
    storeName: "Home Essentials",
    title: "10% Off Furniture",
    description: "Upgrade your living room with 10% off all furniture items.",
    code: "HOME10",
    discount: "10% OFF",
    category: "Home",
    expirationDate: "2026-08-31",
    verified: true,
    featured: false,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 6,
    storeName: "Glowing Beauty",
    title: "Free Shipping on Orders $35+",
    description: "Get free standard shipping on all orders over $35.",
    code: "FREESHIP",
    discount: "FREE SHIPPING",
    category: "Beauty",
    expirationDate: "2027-01-01",
    verified: true,
    featured: true,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 7,
    storeName: "Fresh Grocery",
    title: "$10 Off $50 Groceries",
    description: "Save $10 on your first grocery delivery of $50 or more.",
    code: "FRESH10",
    discount: "$10 OFF",
    category: "Grocery",
    expirationDate: "2026-12-15",
    verified: true,
    featured: false,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 8,
    storeName: "Vitamin Shoppe Plus",
    title: "Buy 1 Get 1 50% Off",
    description: "Mix and match select vitamins and supplements.",
    code: "BOGO50",
    discount: "BOGO 50%",
    category: "Health & Wellness",
    expirationDate: "2026-10-31",
    verified: true,
    featured: false,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 9,
    storeName: "Silver Pharmacy",
    title: "15% Off Prescriptions",
    description: "Special savings for seniors on selected prescription refills.",
    code: "SENIOR15",
    discount: "15% OFF",
    category: "Health & Wellness",
    expirationDate: "2026-12-31",
    verified: true,
    featured: true,
    seniorOnly: true,
    url: "#",
    active: true
  },
  {
    id: 10,
    storeName: "Grandpa's Diner",
    title: "20% Off Tuesday Breakfast",
    description: "Seniors get 20% off breakfast menu every Tuesday morning.",
    code: "TUESDAY20",
    discount: "20% OFF",
    category: "Food",
    expirationDate: "2026-11-30",
    verified: true,
    featured: false,
    seniorOnly: true,
    url: "#",
    active: true
  },
  {
    id: 11,
    storeName: "Comfort Shoes",
    title: "10% Off Orthopedic Footwear",
    description: "Seniors receive 10% off all orthopedic and comfort shoes.",
    code: "WALKEASY",
    discount: "10% OFF",
    category: "Fashion",
    expirationDate: "2026-10-01",
    verified: true,
    featured: false,
    seniorOnly: true,
    url: "#",
    active: true
  },
  {
    id: 12,
    storeName: "Tech Haven",
    title: "10% Off Senior Tech Support",
    description: "Discounted in-home tech support for seniors.",
    code: "TECHSENIOR",
    discount: "10% OFF",
    category: "Electronics",
    expirationDate: "2026-12-31",
    verified: true,
    featured: false,
    seniorOnly: true,
    url: "#",
    active: true
  },
  {
    id: 13,
    storeName: "Example Fashion",
    title: "Expired 50% Off Clearance",
    description: "Massive savings on all clearance items. (This coupon has expired)",
    code: "CLEAR50",
    discount: "50% OFF",
    category: "Fashion",
    expirationDate: "2023-01-01",
    verified: false,
    featured: false,
    seniorOnly: false,
    url: "#",
    active: true
  },
  {
    id: 14,
    storeName: "Sunny Vacations",
    title: "Senior Discount on Cruises",
    description: "Seniors 65+ save $100 on any 7-day Caribbean cruise.",
    code: "CRUISE100",
    discount: "$100 OFF",
    category: "Travel",
    expirationDate: "2027-05-30",
    verified: true,
    featured: true,
    seniorOnly: true,
    url: "#",
    active: true
  },
  {
    id: 15,
    storeName: "MegaMart",
    title: "5% Off Senior Days",
    description: "Every Wednesday, seniors save 5% on their entire grocery bill.",
    code: "WEDSAVE",
    discount: "5% OFF",
    category: "Grocery",
    expirationDate: "2026-12-31",
    verified: true,
    featured: false,
    seniorOnly: true,
    url: "#",
    active: true
  },
  {
    id: 16,
    storeName: "Auto Parts Pro",
    title: "20% Off Brake Pads",
    description: "Get ready for a road trip with 20% off all premium brake pads.",
    code: "BRAKE20",
    discount: "20% OFF",
    category: "Automotive",
    expirationDate: "2026-09-15",
    verified: true,
    featured: false,
    seniorOnly: false,
    url: "#",
    active: true
  }
];
